name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Print a message to verify the workflow
      - name: Test Workflow Trigger
        run: echo "Pull request workflow triggered successfully!"
